/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractFilterCode } from '../../icc-api/model/AbstractFilterCode'

export class AllCodesFilter extends AbstractFilterCode {
  $type: string = 'AllCodesFilter'
  constructor(json: JSON | any) {
    super(json)
    Object.assign(this as AllCodesFilter, json)
  }

  desc?: string
}
