/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractFilterHealthElement } from '../../icc-api/model/AbstractFilterHealthElement'

/**
 * Retrieves the HealthElements that have in their qualifiedLinks, for any type of qualification, a link
 * with an association id equal to associationId.
 * As HealthElement is an encryptable entity and this filter does not specify a data owner id, a special
 * permission is required to use this filter.
 */
export class HealthElementByAssociationIdFilter extends AbstractFilterHealthElement {
  $type: string = 'HealthElementByAssociationIdFilter'
  constructor(json: JSON | any) {
    super(json)

    Object.assign(this as HealthElementByAssociationIdFilter, json)
  }

  associationId?: string
}
