/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AbstractFilterPatient } from '../../icc-api/model/AbstractFilterPatient'

export class PatientByHcPartyAndExternalIdFilter extends AbstractFilterPatient {
  $type: string = 'PatientByHcPartyAndExternalIdFilter'
  constructor(json: JSON | any) {
    super(json)

    Object.assign(this as PatientByHcPartyAndExternalIdFilter, json)
  }

  desc?: string
  externalId?: string
  healthcarePartyId?: string
}
