/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AllCodesFilter } from './AllCodesFilter'
import { AllDevicesFilter } from './AllDevicesFilter'
import { AllHealthcarePartiesFilter } from './AllHealthcarePartiesFilter'
import { AllUsersFilter } from './AllUsersFilter'
import { CodeByIdsFilter } from './CodeByIdsFilter'
import { CodeByRegionTypeLabelLanguageFilter } from './CodeByRegionTypeLabelLanguageFilter'
import { ContactByHcPartyFilter } from './ContactByHcPartyFilter'
import { ContactByHcPartyPatientTagCodeDateFilter } from './ContactByHcPartyPatientTagCodeDateFilter'
import { ContactByHcPartyTagCodeDateFilter } from './ContactByHcPartyTagCodeDateFilter'
import { ContactByServiceIdsFilter } from './ContactByServiceIdsFilter'
import { DeviceByHcPartyFilter } from './DeviceByHcPartyFilter'
import { DeviceByIdsFilter } from './DeviceByIdsFilter'
import { HealthElementByHcPartyFilter } from './HealthElementByHcPartyFilter'
import { HealthElementByHcPartyIdentifiersFilter } from './HealthElementByHcPartyIdentifiersFilter'
import { HealthElementByHcPartySecretForeignKeysFilter } from './HealthElementByHcPartySecretForeignKeysFilter'
import { HealthElementByHcPartyTagCodeFilter } from './HealthElementByHcPartyTagCodeFilter'
import { HealthElementByIdsFilter } from './HealthElementByIdsFilter'
import { HealthcarePartyByIdsFilter } from './HealthcarePartyByIdsFilter'
import { InvoiceByHcPartyCodeDateFilter } from './InvoiceByHcPartyCodeDateFilter'
import { PatientByHcPartyAndActiveFilter } from './PatientByHcPartyAndActiveFilter'
import { PatientByHcPartyAndExternalIdFilter } from './PatientByHcPartyAndExternalIdFilter'
import { PatientByHcPartyAndIdentifiersFilter } from './PatientByHcPartyAndIdentifiersFilter'
import { PatientByHcPartyAndSsinFilter } from './PatientByHcPartyAndSsinFilter'
import { PatientByHcPartyAndSsinsFilter } from './PatientByHcPartyAndSsinsFilter'
import { PatientByHcPartyDateOfBirthBetweenFilter } from './PatientByHcPartyDateOfBirthBetweenFilter'
import { PatientByHcPartyDateOfBirthFilter } from './PatientByHcPartyDateOfBirthFilter'
import { PatientByHcPartyFilter } from './PatientByHcPartyFilter'
import { PatientByHcPartyGenderEducationProfession } from './PatientByHcPartyGenderEducationProfession'
import { PatientByHcPartyNameContainsFuzzyFilter } from './PatientByHcPartyNameContainsFuzzyFilter'
import { PatientByHcPartyNameFilter } from './PatientByHcPartyNameFilter'
import { PatientByIdsFilter } from './PatientByIdsFilter'
import { ServiceByContactsAndSubcontactsFilter } from './ServiceByContactsAndSubcontactsFilter'
import { ServiceByHcPartyFilter } from './ServiceByHcPartyFilter'
import { ServiceByHcPartyIdentifiersFilter } from './ServiceByHcPartyIdentifiersFilter'
import { ServiceByHcPartyTagCodeDateFilter } from './ServiceByHcPartyTagCodeDateFilter'
import { ServiceByIdsFilter } from './ServiceByIdsFilter'
import { ServiceBySecretForeignKeys } from './ServiceBySecretForeignKeys'
import { UserByIdsFilter } from './UserByIdsFilter'

export class FilterDefinitions {
  constructor(json: JSON | any) {
    Object.assign(this as FilterDefinitions, json)
  }

  allCodesFilter?: AllCodesFilter
  codeByIdsFilter?: CodeByIdsFilter
  codeByRegionTypeLabelLanguageFilter?: CodeByRegionTypeLabelLanguageFilter
  contactByHcPartyFilter?: ContactByHcPartyFilter
  contactByHcPartyPatientTagCodeDateFilter?: ContactByHcPartyPatientTagCodeDateFilter
  contactByHcPartyTagCodeDateFilter?: ContactByHcPartyTagCodeDateFilter
  contactByServiceIdsFilter?: ContactByServiceIdsFilter
  allDevicesFilter?: AllDevicesFilter
  deviceByHcPartyFilter?: DeviceByHcPartyFilter
  deviceByIdsFilter?: DeviceByIdsFilter
  allHealthcarePartiesFilter?: AllHealthcarePartiesFilter
  healthcarePartyByIdsFilter?: HealthcarePartyByIdsFilter
  healthElementByHcPartyFilter?: HealthElementByHcPartyFilter
  healthElementByHcPartyIdentifiersFilter?: HealthElementByHcPartyIdentifiersFilter
  healthElementByHcPartySecretForeignKeysFilter?: HealthElementByHcPartySecretForeignKeysFilter
  healthElementByHcPartyTagCodeFilter?: HealthElementByHcPartyTagCodeFilter
  healthElementByIdsFilter?: HealthElementByIdsFilter
  invoiceByHcPartyCodeDateFilter?: InvoiceByHcPartyCodeDateFilter
  patientByHcPartyAndActiveFilter?: PatientByHcPartyAndActiveFilter
  patientByHcPartyAndExternalIdFilter?: PatientByHcPartyAndExternalIdFilter
  patientByHcPartyAndIdentifiersFilter?: PatientByHcPartyAndIdentifiersFilter
  patientByHcPartyAndSsinFilter?: PatientByHcPartyAndSsinFilter
  patientByHcPartyAndSsinsFilter?: PatientByHcPartyAndSsinsFilter
  patientByHcPartyDateOfBirthBetweenFilter?: PatientByHcPartyDateOfBirthBetweenFilter
  patientByHcPartyDateOfBirthFilter?: PatientByHcPartyDateOfBirthFilter
  patientByHcPartyFilter?: PatientByHcPartyFilter
  patientByHcPartyGenderEducationProfession?: PatientByHcPartyGenderEducationProfession
  patientByHcPartyNameContainsFuzzyFilter?: PatientByHcPartyNameContainsFuzzyFilter
  patientByHcPartyNameFilter?: PatientByHcPartyNameFilter
  patientByIdsFilter?: PatientByIdsFilter
  serviceByContactsAndSubcontactsFilter?: ServiceByContactsAndSubcontactsFilter
  serviceByHcPartyFilter?: ServiceByHcPartyFilter
  serviceByHcPartyIdentifiersFilter?: ServiceByHcPartyIdentifiersFilter
  serviceByHcPartyTagCodeDateFilter?: ServiceByHcPartyTagCodeDateFilter
  serviceByIdsFilter?: ServiceByIdsFilter
  serviceBySecretForeignKeys?: ServiceBySecretForeignKeys
  allUsersFilter?: AllUsersFilter
  userByIdsFilter?: UserByIdsFilter
}
