/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The healthcare party's status history
 */
import { decodeBase64 } from "./ModelHelper"

export class HealthcarePartyHistoryStatusDto {
  constructor(json: JSON | any) {
    Object.assign(this as HealthcarePartyHistoryStatusDto, json)
  }

  status?: HealthcarePartyHistoryStatusDto.StatusEnum
  specialisationCode?: string
  startDate?: number
  active?: boolean
}
export namespace HealthcarePartyHistoryStatusDto {
  export type StatusEnum = "trainee" | "withconvention" | "accreditated"
  export const StatusEnum = {
    Trainee: "trainee" as StatusEnum,
    Withconvention: "withconvention" as StatusEnum,
    Accreditated: "accreditated" as StatusEnum,
  }
}
