/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStub } from './CodeStub'
import {ReferenceRange} from "./ReferenceRange"

export class Measure {
  constructor(json: JSON | any) {

    if (!!json?.min || !!json?.max) {
      json.referenceRange = [
        new ReferenceRange({
          low: json.min,
          high: json.max
        })
      ]
      delete json?.min
      delete json?.max
    }

    Object.assign(this as Measure, json)
  }

  value?: number
  ref?: number
  severity?: number
  severityCode?: string
  evolution?: number
  unit?: string
  sign?: string
  unitCodes?: Array<CodeStub>
  comment?: string
  comparator?: string
  /**
   * Reference range for the measure
   */
  referenceRange?: Array<ReferenceRange>
}
