/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityTemplate } from './EntityTemplate'
import { PaginatedDocumentKeyIdPairObject } from './PaginatedDocumentKeyIdPairObject'

export class PaginatedListEntityTemplate {
  constructor(json: JSON | any) {
    Object.assign(this as PaginatedListEntityTemplate, json)
  }

  pageSize?: number
  totalSize?: number
  rows?: Array<EntityTemplate>
  nextKeyPair?: PaginatedDocumentKeyIdPairObject
}
