/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityTemplateDto } from "./EntityTemplateDto"
import { PaginatedDocumentKeyIdPairObject } from "./PaginatedDocumentKeyIdPairObject"

import { decodeBase64 } from "./ModelHelper"

export class PaginatedListEntityTemplateDto {
  constructor(json: JSON | any) {
    Object.assign(this as PaginatedListEntityTemplateDto, json)
  }

  pageSize?: number
  totalSize?: number
  rows?: Array<EntityTemplateDto>
  nextKeyPair?: PaginatedDocumentKeyIdPairObject
}
