/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SamTextDto } from "./SamTextDto"
import { StandardSubstanceDto } from "./StandardSubstanceDto"

import { decodeBase64 } from "./ModelHelper"

export class SubstanceDto {
  constructor(json: JSON | any) {
    Object.assign(this as SubstanceDto, json)
  }

  id?: string
  rev?: string
  /**
   * hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
   */
  deletionDate?: number
  code?: string
  chemicalForm?: string
  name?: SamTextDto
  note?: SamTextDto
  standardSubstances?: Array<StandardSubstanceDto>
}
