/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from './XHR'
import { Agenda } from '../model/Agenda'
import { User } from '../model/User'

export class IccAnonymousAccessApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(host: string, headers: any, fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>) {
    this.host = host
    this.headers = Object.keys(headers).map((k) => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }

  /**
   *
   * @summary Get Availabilities for HCP and agendaId
   * @param groupId
   * @param agendaId
   * @param startDate
   * @param endDate
   * @param hcpId
   * @param duration
   * @param limit
   */
  getAvailabilitiesByPeriodAndAgendaId(
    groupId: string,
    agendaId: string,
    startDate: number,
    endDate: number,
    hcpId: string,
    duration: number,
    limit?: number
  ): Promise<Array<number>> {
    let _body = null

    const _url =
      this.host +
      `/aa/available/inGroup/${encodeURIComponent(String(groupId))}/agenda/${encodeURIComponent(String(agendaId))}` +
      '?ts=' +
      new Date().getTime() +
      (startDate ? '&startDate=' + encodeURIComponent(String(startDate)) : '') +
      (endDate ? '&endDate=' + encodeURIComponent(String(endDate)) : '') +
      (hcpId ? '&hcpId=' + encodeURIComponent(String(hcpId)) : '') +
      (duration ? '&duration=' + encodeURIComponent(String(duration)) : '') +
      (limit ? '&limit=' + encodeURIComponent(String(limit)) : '')
    let headers = this.headers
    return XHR.sendCommand('GET', _url, headers, _body, this.fetchImpl)
      .then((doc) => (doc.body as Array<JSON>).map((it) => JSON.parse(JSON.stringify(it))))
      .catch((err) => this.handleError(err))
  }

  /**
   * Returns a list of Agendas cfor the provided user and group
   * @summary List Agendas for a provided group id
   * @param groupId Healthcare parties group id
   * @param userId Healthcare party user id
   */
  listAgendasInHealthcareParty(groupId: string, userId: string): Promise<Array<Agenda>> {
    let _body = null

    const _url =
      this.host +
      `/aa/agenda/inGroup/${encodeURIComponent(String(groupId))}/forUser/${encodeURIComponent(String(userId))}` +
      '?ts=' +
      new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand('GET', _url, headers, _body, this.fetchImpl)
      .then((doc) => (doc.body as Array<JSON>).map((it) => new Agenda(it)))
      .catch((err) => this.handleError(err))
  }

  /**
   * Returns a list of healthcare parties contained in the group owning the providing id
   * @summary List healthcare parties for a provided group id
   * @param groupId Healthcare parties group id
   */
  listHealthcarePartiesInGroup(groupId: string): Promise<Array<User>> {
    let _body = null

    const _url = this.host + `/aa/hcparty/inGroup/${encodeURIComponent(String(groupId))}` + '?ts=' + new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand('GET', _url, headers, _body, this.fetchImpl)
      .then((doc) => (doc.body as Array<JSON>).map((it) => new User(it)))
      .catch((err) => this.handleError(err))
  }
}
