/**
 * iCure Data Stack API Documentation
 * The iCure Data Stack Application API is the native interface to iCure. This version is obsolete, please use v2.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from './XHR'
import { DocIdentifier } from '../model/DocIdentifier'
import { Place } from '../model/Place'
import { AuthenticationProvider, NoAuthenticationProvider } from '../../icc-x-api'
import { iccRestApiPath } from './IccRestApiPath'
import { ApiVersion, getApiVersionFromUrl } from '../utils/api-version'
import { ListOfIds } from '../model/ListOfIds'

export class IccPlaceApi {
  host: string
  headers: Array<XHR.Header>
  authenticationProvider: AuthenticationProvider
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(
    host: string,
    headers: any,
    authenticationProvider?: AuthenticationProvider,
    fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>
  ) {
    this.host = iccRestApiPath(host)
    this.headers = Object.keys(headers).map((k) => new XHR.Header(k, headers[k]))
    this.authenticationProvider = !!authenticationProvider ? authenticationProvider : new NoAuthenticationProvider()
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }

  /**
   *
   * @summary Creates a place
   * @param body
   */
  createPlace(body?: Place): Promise<Place> {
    let _body = null
    _body = body

    const _url = this.host + `/place` + '?ts=' + new Date().getTime()
    let headers = this.headers
    headers = headers.filter((h) => h.header !== 'Content-Type').concat(new XHR.Header('Content-Type', 'application/json'))
    return XHR.sendCommand('POST', _url, headers, _body, this.fetchImpl, undefined, this.authenticationProvider.getAuthService())
      .then((doc) => new Place(doc.body as JSON))
      .catch((err) => this.handleError(err))
  }

  /**
   * @summary Deletes a batch of places.
   *
   * @param placeIds an array containing the ids of the places to delete.
   * @return a Promise that will resolve in an array of DocIdentifiers of the successfully deleted places.
   */
  deletePlaces(placeIds: string[]): Promise<Array<DocIdentifier>> {
    const response =
      getApiVersionFromUrl(this.host) == ApiVersion.V1
        ? XHR.sendCommand(
            'DELETE',
            this.host + `/place/${encodeURIComponent(placeIds.join(','))}` + '?ts=' + new Date().getTime(),
            this.headers,
            null,
            this.fetchImpl,
            undefined,
            this.authenticationProvider.getAuthService()
          )
        : XHR.sendCommand(
            'POST',
            this.host + `/place/delete/batch` + '?ts=' + new Date().getTime(),
            this.headers.filter((h) => h.header !== 'Content-Type').concat(new XHR.Header('Content-Type', 'application/json')),
            new ListOfIds({ ids: placeIds }),
            this.fetchImpl,
            undefined,
            this.authenticationProvider.getAuthService()
          )

    return response.then((doc) => (doc.body as Array<JSON>).map((it) => new DocIdentifier(it))).catch((err) => this.handleError(err))
  }

  /**
   *
   * @summary Gets a place
   * @param placeId
   */
  getPlace(placeId: string): Promise<Place> {
    let _body = null

    const _url = this.host + `/place/${encodeURIComponent(String(placeId))}` + '?ts=' + new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand('GET', _url, headers, _body, this.fetchImpl, undefined, this.authenticationProvider.getAuthService())
      .then((doc) => new Place(doc.body as JSON))
      .catch((err) => this.handleError(err))
  }

  /**
   *
   * @summary Gets all places
   */
  getPlaces(): Promise<Array<Place>> {
    let _body = null

    const _url = this.host + `/place` + '?ts=' + new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand('GET', _url, headers, _body, this.fetchImpl, undefined, this.authenticationProvider.getAuthService())
      .then((doc) => (doc.body as Array<JSON>).map((it) => new Place(it)))
      .catch((err) => this.handleError(err))
  }

  /**
   *
   * @summary Modifies an place
   * @param body
   */
  modifyPlace(body?: Place): Promise<Place> {
    let _body = null
    _body = body

    const _url = this.host + `/place` + '?ts=' + new Date().getTime()
    let headers = this.headers
    headers = headers.filter((h) => h.header !== 'Content-Type').concat(new XHR.Header('Content-Type', 'application/json'))
    return XHR.sendCommand('PUT', _url, headers, _body, this.fetchImpl, undefined, this.authenticationProvider.getAuthService())
      .then((doc) => new Place(doc.body as JSON))
      .catch((err) => this.handleError(err))
  }
}
