name: Release management

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
      - 'support/**'

jobs:
  if_merged:
    name: Build & Publish to NPM
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'SemVer.Major') || contains(github.event.pull_request.labels.*.name, 'SemVer.Minor') || contains(github.event.pull_request.labels.*.name, 'SemVer.Patch'))
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: git config --global user.email "dev@icure.com"
      - run: git config --global user.name "iCure"
      - name: Setup Node ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - name: Install dependencies, test and build 🔧
        run: yarn install --frozen-lockfile && yarn run build
      - name: Creation new version (Major) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'SemVer.Major') }}
        run: yarn version --major
      - name: Creation new version (Minor) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'SemVer.Minor') }}
        run: yarn version --minor
      - name: Creation new version (Patch) 🏷️
        if: ${{ contains(github.event.pull_request.labels.*.name, 'SemVer.Patch') }}
        run: yarn version --patch
      - name: Push commit and tag ↗️
        run: git push --follow-tags -f
      - name: Set LATEST_TAG environment variable ⚙️
        run: |
          latestTag="$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) | sed 's/v//')"

          echo 'LATEST_TAG='$latestTag >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish package on NPM 📦
        run: yarn run prepare && cd dist && yarn publish --no-git-tag-version --new-version $LATEST_TAG && cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release_note:
    name: Release note
    needs: [if_merged]
    runs-on: ubuntu-latest
    env:
      REPO: icure/icure-typescript-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch git history ⚙️
        run: git fetch --prune --unshallow
      - name: Set LATEST_TAG environment variable ⚙️
        run: |
          latestTag="$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) | sed 's/v//')"
          currentBranch="$(git branch --show-current)"

          echo 'LATEST_TAG='$latestTag >> $GITHUB_ENV
          echo 'CURRENT_BRANCH='$currentBranch >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create a release 📝
        run: gh api --method POST /repos/$REPO/releases -f tag_name="$LATEST_TAG" -f target_commitish="$CURRENT_BRANCH" -f name="$LATEST_TAG" -F draft=false -F generate_release_notes=true -F prerelease=false
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
